# Generated by Django 4.0.3 on 2022-03-23 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_disciplina', models.CharField(max_length=255, verbose_name='NOME DISCIPLINA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_funcao', models.CharField(max_length=255, verbose_name='NOME')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_status', models.CharField(max_length=255, verbose_name='STATUS')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arq', models.FileField(help_text='localizar Arquivo', upload_to='uploads/')),
                ('update_arq', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='NOME')),
                ('data_contrato', models.DateField(blank=True, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='uploads/photos/', verbose_name='FOTO')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('controle_func', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.funcao', verbose_name='FUNÇÃO')),
            ],
        ),
        migrations.CreateModel(
            name='ControleProf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controle_proj1', models.CharField(max_length=255, verbose_name='PROJETO ATUAL')),
                ('controle_proj2', models.CharField(max_length=255, verbose_name='PROJETO ANTERIOR')),
                ('controle_obs', models.CharField(max_length=255, verbose_name='OBS')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('controle_disc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.disciplina', verbose_name='DISCIPLINA')),
                ('controle_func', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.funcao', verbose_name='FUNÇÃO')),
                ('controle_nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.profissional', verbose_name='NOME')),
                ('controle_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.status', verbose_name='STATUS')),
            ],
        ),
    ]
